# Generated by Django 4.2.13 on 2024-07-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDescription',
        ),
    ]
