# Generated by Django 4.2.13 on 2024-07-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rename_variantdescription_variantoptions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variantoptions',
            table='inventory_variant_options',
        ),
    ]
