# Generated by Django 4.2.13 on 2024-09-22 15:34

import apps.inventory.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0016_alter_item_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantOptions',
            new_name='VariantOption',
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.item_picture_path),
        ),
        migrations.AlterField(
            model_name='variant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='variantoption',
            table='inventory_variant_option',
        ),
    ]
