# Generated by Django 4.2.13 on 2024-11-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_variantoptions_variantoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
    ]
