# Generated by Django 4.2.13 on 2024-11-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_item_supplier_delete_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='created_by',
        ),
    ]
