# Generated by Django 4.2.13 on 2024-11-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_user_category_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='user',
            new_name='created_by',
        ),
    ]
