# Generated by Django 4.2.13 on 2024-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_rename_user_item_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
