# Generated by Django 4.2.13 on 2024-07-02 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_is_confirmed_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_code_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e59cef1e-25ac-4ef8-b82c-c5b507b66d1f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
