# Generated by Django 4.2.13 on 2024-07-02 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_id_alter_user_recovery_code_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recovery_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recovery_code_created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('32304d27-35ea-4a1f-9d2d-17e9674ff4d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
