# Generated by Django 4.2.13 on 2024-09-09 14:36

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=apps.base.models.user_avatar_path),
        ),
    ]
