# Generated by Django 4.2.13 on 2024-11-14 14:48

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_user_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.base.models.user_avatar_path),
        ),
    ]
