# Generated by Django 4.2.13 on 2025-01-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
