# Generated by Django 4.2.13 on 2025-01-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_activity_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='object_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='object_ref',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
