# Generated by Django 4.2.13 on 2025-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_activity_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_ref',
            field=models.JSONField(default=list),
        ),
    ]
