# Generated by Django 4.2.13 on 2024-10-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0004_client_updated_order_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='source_of_acquisition',
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.ForeignKey(help_text='The source through which this client was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_clients', to='client_orders.acquisitionsource'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.ForeignKey(help_text='The source through which this order was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_orders', to='client_orders.acquisitionsource'),
        ),
    ]
