# Generated by Django 4.2.13 on 2024-11-04 14:46

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0011_alter_city_name_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=7, max_length=12, prefix='ID_'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_orders.location'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source through which this client was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_clients', to='client_orders.acquisitionsource'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='client_orders.client'),
        ),
    ]
