# Generated by Django 4.2.13 on 2024-11-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0012_order_reference_id_alter_client_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='ClientOrderStatus',
        ),
        migrations.AlterModelOptions(
            name='acquisitionsource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='clientorderstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ['created_at']},
        ),
    ]
