# Generated by Django 4.2.13 on 2024-11-13 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0018_alter_category_options_alter_supplier_options'),
        ('client_orders', '0014_rename_order_clientorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='ClientOrderedItem',
        ),
    ]
