# Generated by Django 4.2.13 on 2024-11-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_category_options_alter_supplier_options'),
        ('client_orders', '0015_rename_ordereditem_clientordereditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='client_orders.client'),
        ),
        migrations.AlterField(
            model_name='clientordereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
    ]
