# Generated by Django 4.2.13 on 2024-11-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0018_rename_clientorderstatus_orderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='payment_status',
            field=models.ForeignKey(blank=True, default='8ccdc2f8-1d6e-489f-81cf-7df3c4fce245', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_payment_status', to='client_orders.orderstatus'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_status',
            field=models.ForeignKey(blank=True, default='8ccdc2f8-1d6e-489f-81cf-7df3c4fce245', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_delivery_status', to='client_orders.orderstatus'),
        ),
    ]
