# Generated by Django 4.2.13 on 2024-12-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_shipping_cost'),
        ('client_orders', '0019_clientorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='sales.sale'),
        ),
    ]
