# Generated by Django 4.2.13 on 2024-12-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_shipping_cost'),
        ('client_orders', '0020_clientorder_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_orders.location'),
        ),
    ]
