# Generated by Django 4.2.13 on 2025-01-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0021_alter_clientorder_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The source through which this order was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_orders', to='client_orders.acquisitionsource'),
        ),
    ]
