# Generated by Django 4.2.13 on 2024-11-17 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import utils.tokens


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderStatus',
            fields=[
                ('id', models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='reference_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=7, max_length=12, prefix='ID_'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='supplier_orders.supplier'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_orders.supplierorderstatus'),
        ),
    ]
