# Generated by Django 4.2.13 on 2024-11-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0018_rename_clientorderstatus_orderstatus_and_more'),
        ('supplier_orders', '0002_supplierorderstatus_supplierorder_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorder',
            name='status',
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='delivery_status',
            field=models.ForeignKey(blank=True, default='8ccdc2f8-1d6e-489f-81cf-7df3c4fce245', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status', to='client_orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='payment_status',
            field=models.ForeignKey(blank=True, default='8ccdc2f8-1d6e-489f-81cf-7df3c4fce245', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status', to='client_orders.orderstatus'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for the shipment', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SupplierOrderStatus',
        ),
    ]
