# Generated by Django 4.2.13 on 2024-11-19 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.tokens


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_rename_user_item_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_orders', '0004_alter_supplierorder_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderedItem',
            fields=[
                ('id', models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ordered_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_items', to='inventory.item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_orders.supplierorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
