# Generated by Django 4.2.13 on 2024-11-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_orders', '0005_supplierordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierordereditem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_items', to='supplier_orders.supplier'),
        ),
    ]
