# Generated by Django 4.2.13 on 2024-12-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_item_supplier'),
        ('supplier_orders', '0006_supplierordereditem_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierordereditem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='supplierordereditem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='supplier_orders.supplierorder'),
        ),
    ]
