# Generated by Django 4.2.13 on 2024-06-26 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6c9fc737-5cda-44cc-b7a2-65a1696f07c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
