# Generated by Django 4.2.13 on 2024-06-26 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('470109b5-7156-474c-88a0-5f3ce4041fd1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
