# Generated by Django 4.2.13 on 2024-07-02 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_recovery_code_user_recovery_code_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d408382e-f0d3-40c3-9d80-e8f1a07558b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='recovery_code_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
