# Generated by Django 4.2.13 on 2024-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_user_recovery_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='3140a489-4a82-450d-b67e-26adb5711d0e', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
