# Generated by Django 4.2.13 on 2024-09-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_code_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
    ]
