# Generated by Django 4.2.13 on 2024-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default='5fd12f93-f939-4544-888a-f1e465e77b9d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default='5fd12f93-f939-4544-888a-f1e465e77b9d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.UUIDField(default='5fd12f93-f939-4544-888a-f1e465e77b9d', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
