# Generated by Django 4.2.13 on 2024-07-06 18:58

from django.db import migrations, models
import utils.tokens


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_id_alter_product_id_alter_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
