# Generated by Django 4.2.13 on 2024-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_addattr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
