# Generated by Django 4.2.13 on 2024-07-27 16:39
from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_product_updated'),
    ]

    operations = [
        # Rename Product to Item
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        # Rename AddAttrDescription to VariantDescription
        migrations.RenameModel(
            old_name='AddAttrDescription',
            new_name='VariantDescription',
        ),
        # Rename AddAttr to Variant
        migrations.RenameModel(
            old_name='AddAttr',
            new_name='Variant',
        ),
        # Rename Field other_attr to variants in Item model
        migrations.RenameField(
            model_name='item',
            old_name='other_attr',
            new_name='variants',
        ),
        # Rename Field product to item in VariantDescription model
        migrations.RenameField(
            model_name='variantdescription',
            old_name='product',
            new_name='item',
        ),
        # Rename Field add_attr to variant in VariantDescription model
        migrations.RenameField(
            model_name='variantdescription',
            old_name='add_attr',
            new_name='variant',
        ),
        # Change Table Name for VariantDescription
        migrations.AlterModelTable(
            name='variantdescription',
            table='inventory_variant_description',
        ),
        # Change Table Name for Variant
        migrations.AlterModelTable(
            name='variant',
            table='inventory_variant',
        ),
    ]
