# Generated by Django 4.2.13 on 2024-07-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_item_variantdescription_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantDescription',
            new_name='VariantOptions',
        ),
        migrations.AlterField(
            model_name='item',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='variants', to='inventory.variant'),
        ),
    ]
