# Generated by Django 4.2.13 on 2024-06-26 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a46126a-0199-48e1-87a0-68d468f933c1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
