# Generated by Django 4.2.13 on 2024-07-01 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_managers_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='base/images/pfp/default.jpg', null=True, upload_to='base/images/pfp/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdf6120e-1dc2-4888-adc3-5b373b0d477b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
