# Generated by Django 4.2.13 on 2024-07-02 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_confirm_code_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_code_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a99c0cc4-c0d5-43fe-ab2a-97169ccd4a09'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
