# Generated by Django 4.2.13 on 2024-12-09 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import utils.tokens


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0023_alter_item_supplier'),
        ('client_orders', '0019_clientorder_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=7, max_length=12, prefix='ID_')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('from_order', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=False)),
                ('client', models.ForeignKey(help_text='The client this sale is associated with', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='client_orders.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this sale', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('delivery_status', models.ForeignKey(blank=True, default='8ccdc2f8-1d6e-489f-81cf-7df3c4fce245', on_delete=django.db.models.deletion.PROTECT, related_name='sale_delivery_status', to='client_orders.orderstatus')),
                ('payment_status', models.ForeignKey(blank=True, default='8ccdc2f8-1d6e-489f-81cf-7df3c4fce245', on_delete=django.db.models.deletion.PROTECT, related_name='sale_payment_status', to='client_orders.orderstatus')),
                ('shipping_address', models.ForeignKey(help_text='The address to ship the items sold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='client_orders.location')),
                ('source', models.ForeignKey(blank=True, help_text='The source through which this sale was acquired', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='client_orders.acquisitionsource')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.UUIDField(default=utils.tokens.Token.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
