# Generated by Django 4.2.13 on 2024-12-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0019_clientorder_payment_status_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(help_text='The client this sale is associated with', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='client_orders.client'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='sales.sale'),
        ),
    ]
