# Generated by Django 4.2.13 on 2024-12-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_tracking_number_alter_sale_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
