# Generated by Django 4.2.13 on 2024-12-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='from_order',
        ),
    ]
